version: 1.0.{build}
image:
- Visual Studio 2015
configuration:
- Debug
clone_depth: 1
cache:
- packages -> **\packages.config
- Web/bower_components
- Web/node_modules
install:
- choco install -y sandcastle
environment:
  SHFBROOT: c:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder
before_build:
- cmd: nuget restore
build:
  project: SkeletonMvc.sln
  parallel: true
  verbosity: minimal
deploy_script:
- ps1: deploy_docs.ps1