version: 1.0.{build}
image:
- Visual Studio 2015
configuration:
- Debug
clone_depth: 1
cache:
- packages -> **\packages.config
- Web/bower_components
- Web/node_modules
- '%LocalAppData%\NuGet\Cache'
install:
- choco install -y powershell
- choco install -y sandcastle
environment:
  SHFBROOT: c:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder
before_build:
- cmd: nuget restore
build:
  project: SkeletonMvc.sln
  parallel: true
  verbosity: minimal
deploy_script:
- cd Documentation/Help
- git config --global user.email $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL
- git config --global user.name $env:APPVEYOR_REPO_COMMIT_AUTHOR
- git clone --branch=gh-pages https://www.github.com/mcnultyyy/SkeletonMvc gh-pages
- git add .
- Set-Variable message ([string]::Format("CI autocommit from commit {0}", $env:APPVEYOR_REPO_COMMIT))
- git commit -m $message
- git push