version: 1.0.{build}
image:
- Visual Studio 2015
configuration:
- Debug
clone_depth: 1
cache:
- packages -> **\packages.config
- Web/bower_components
- Web/node_modules
- '%LocalAppData%\NuGet\Cache'
install:
- choco install -y powershell
- choco install -y sandcastle
environment:
  SHFBROOT: c:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder
  GH_TOKEN:
    secure: BGc9FE1XSc+IQdp11BWC1ISgt7ucp4DinsKlJL4XM5ngc4oComC4D4s2+/EXY7XM
before_build:
- cmd: nuget restore
build:
  project: SkeletonMvc.sln
  parallel: true
  verbosity: minimal
deploy_script:
- cd Documentation
- git config --global credential.helper store
- ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:GH_TOKEN):x-oauth-basic@github.com`n"
- ps: git config --global user.email $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL
- ps: git config --global user.name $env:APPVEYOR_REPO_COMMIT_AUTHOR
- git config --global push.default simple
- git clone --branch=gh-pages https://www.github.com/mcnultyyy/SkeletonMvc gh-pages
- ps: Copy-Item -Path .\Help\* -Destination .\gh-pages\ -Recurse -Force
- cd gh-pages
- git add .
- ps: Set-Variable message ([string]::Format("CI autocommit from commit {0}", $env:APPVEYOR_REPO_COMMIT))
- ps: git commit -m $message
- git push