version: 1.0.{build}
image:
- Visual Studio 2015
configuration:
- Debug
clone_depth: 1
cache:
- packages -> **\packages.config
- Web/bower_components
- Web/node_modules
- '%LocalAppData%\NuGet\Cache'
install:
- choco install -y sandcastle
environment:
  SHFBROOT: c:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder
before_build:
- cmd: nuget restore
build:
  project: SkeletonMvc.sln
  parallel: true
  verbosity: minimal
deploy_script:
- ps1: cd Documentation/Help
- ps1: git config --global user.email $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL
- ps1: git config --global user.name $env:APPVEYOR_REPO_COMMIT_AUTHOR
- ps1: git clone --branch=gh-pages https://www.github.com/mcnultyyy/SkeletonMvc gh-pages
- ps1: git add .
- ps1: $message = "CI autocommit from commit "+$env:APPVEYOR_REPO_COMMIT;
- ps1: git commit -m $message
- ps1: git push